spring:
  application:
    name: TasksTN
  datasource:
    url: jdbc:h2:./database/h2db
    username: user
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: none
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
server:
  port: 8081
