spring:
  application:
    name: TasksTN
  datasource:
    url: jdbc:postgresql://localhost:5444/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: none
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
server:
  port: 8081
